services:
  postgres:
    image: postgres:18-alpine
    container_name: dhaka-tesla-pool-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: dhaka_tesla_pool
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: